add log

diff --git a/files/build_templates/docker_image_ctl.j2 b/files/build_templates/docker_image_ctl.j2
--- a/files/build_templates/docker_image_ctl.j2
+++ b/files/build_templates/docker_image_ctl.j2
@@ -50,10 +50,12 @@ function updateSyslogConf()
     {%- else %}
     sonic-cfggen -d -t /usr/share/sonic/templates/rsyslog-container.conf.j2 -a "{\"target_ip\": \"$TARGET_IP\", \"container_name\": \"$CONTAINER_NAME\" }"  > $TMP_FILE 2>&1
     if [ $? -ne 0 ]; then
+      echo "$CONTAINER_NAME conf gen failed. return code is $?" >> /tmp/chunangli.log
       failed="true"
     fi
     {%- endif %}
     if [ "$failed" == "false"]; then
+      echo "$CONTAINER_NAME conf gen success. falg is $failed. Exec copy." >> /tmp/chunangli.log
       docker cp $TMP_FILE ${DOCKERNAME}:/etc/rsyslog.conf
     fi
 #    rm -rf $TMP_FILE
