Support for package version caching
During the SONiC build, it downloads and installs packages for
multiple build components which includes debian packages, pip modules,
python packages, source code packages, git modules and docker images.
The package versioning feature provides an infrastructure to select
and freeze a particular version of a package.

The package version caching feature provides an infrastructure to cache
the package with the given version into a local storage, so that
subsequent installation will not download from web instead it will load
from local cache path.

The following variable controls the verion caching feature. By default
it is truned off.
    SONIC_VERSION_CACHE_METHOD = [none/cache]
    SONIC_VERSION_CACHE_SOURCE = /path/to/local/storage

diff --git a/src/sonic-build-hooks/hooks/python3 b/src/sonic-build-hooks/hooks/python3
--- a/src/sonic-build-hooks/hooks/python3
+++ b/src/sonic-build-hooks/hooks/python3
@@ -3,9 +3,9 @@
 . /usr/local/share/buildinfo/scripts/buildinfo_base.sh
 
 VERSION_FILE="$BUILDINFO_PATH/versions/versions-py3"
-REAL_COMMAND=$(get_command pip3)
+REAL_COMMAND=$(get_command python3)
 if [ ! -x "$REAL_COMMAND" ]; then
-    echo "The command pip3 not found" 1>&2
+    echo "The command python3 not found" 1>&2
     exit 1
 fi
 
@@ -14,4 +14,4 @@ if [ "$SKIP_BUILD_HOOK" == y ]; then
     exit $?
 fi
 
-PIP_VERSION_FILE=$VERSION_FILE ENABLE_VERSION_CONTROL_PY=$ENABLE_VERSION_CONTROL_PY3 REAL_COMMAND=$REAL_COMMAND run_pip_command "$@"
+PIP_VERSION_FILE=$VERSION_FILE ENABLE_VERSION_CONTROL_PY=$ENABLE_VERSION_CONTROL_PY3 REAL_COMMAND=$REAL_COMMAND run_python_command "$@"
