Refine PR test template
Signed-off-by: Chun'ang Li <chunangli@microsoft.com>

diff --git a/.azure-pipelines/run-test-scheduler-template.yml b/.azure-pipelines/run-test-scheduler-template.yml
--- a/.azure-pipelines/run-test-scheduler-template.yml
+++ b/.azure-pipelines/run-test-scheduler-template.yml
@@ -18,6 +18,10 @@ parameters:
   type: string
   default: 2
 
+- name: NUM_ASIC
+  type: number
+  default: 1
+
 - name: TEST_SET
   type: string
   default: ""
@@ -26,13 +30,81 @@ parameters:
   type: string
   default: ""
 
-- name: MGMT_BRANCH
-  type: string
-  default: master
-
 - name: COMMON_EXTRA_PARAMS
   type: string
   default: ""
+
+- name: VM_TYPE
+  type: string
+  default: "ceos"
+
+- name: TESTBED_NAME
+  type: string
+  default: ""
+
+- name: IMAGE_URL
+  type: string
+  default: ""
+
+- name: HWSKU
+  type: string
+  default: ""
+
+- name: TEST_PLAN_TYPE
+  type: string
+  default: ""
+
+- name: PLATFORM
+  type: string
+  default: ""
+
+- name: SCRIPTS
+  type: string
+  default: ""
+
+- name: FEATURES
+  type: string
+  default: ""
+
+- name: SCRIPTS_EXCLUDE
+  type: string
+  default: ""
+
+- name: FEATURES_EXCLUDE
+  type: string
+  default: ""
+
+- name: REPO_NAME
+  type: string
+  default: ""
+
+- name: MGMT_BRANCH
+  type: string
+  default: ""
+
+- name: STOP_ON_FAILURE
+  type: string
+  default: ""
+
+- name: RETRY_TIMES
+  type: string
+  default: ""
+
+- name: DUMP_KVM_IF_FAIL
+  type: string
+  default: "True"
+  values:
+  - "True"
+  - "False"
+
+- name: REQUESTER
+  type: string
+  default: ""
+
+- name: MAX_RUN_TEST_MINUTES
+  type: number
+  default: 480
+
 
 steps:
   - script: |
@@ -103,18 +175,20 @@ steps:
     env:
       TESTBED_TOOLS_URL: $(TESTBED_TOOLS_URL)
     displayName: Run test
+    timeoutInMinutes: ${{ parameters.MAX_RUN_TEST_MINUTES }}
 
-  - script: |
-      set -e
-      echo "KVM dump"
-      echo "SONiC PR system-level test is powered by SONiC Elastictest, for any issue, please send email to sonicelastictest@microsoft.com"
-      echo "Runtime detailed progress at $(FRONTEND_URL)/scheduler/testplan/$TEST_PLAN_ID "
-      # When "KVMDUMP" finish, it changes into "FAILED", "CANCELLED" or "FINISHED"
-      python ./.azure-pipelines/test_plan.py poll -i "$(TEST_PLAN_ID)" --expected-state KVMDUMP
-    condition: succeededOrFailed()
-    env:
-      TESTBED_TOOLS_URL: $(TESTBED_TOOLS_URL)
-    displayName: KVM dump
+  - ${{ if eq(parameters.DUMP_KVM_IF_FAIL, 'True') }}:
+    - script: |
+        set -e
+        echo "KVM dump"
+        echo "SONiC PR system-level test is powered by SONiC Elastictest, for any issue, please send email to sonicelastictest@microsoft.com"
+        echo "Runtime detailed progress at $(FRONTEND_URL)/scheduler/testplan/$TEST_PLAN_ID "
+        # When "KVMDUMP" finish, it changes into "FAILED", "CANCELLED" or "FINISHED"
+        python ./.azure-pipelines/test_plan.py poll -i "$(TEST_PLAN_ID)" --expected-state KVMDUMP
+      condition: succeededOrFailed()
+      env:
+        TESTBED_TOOLS_URL: $(TESTBED_TOOLS_URL)
+      displayName: KVM dump
 
   - script: |
       set -e
