address pr comments
Signed-off-by: Mai Bui <maibui@microsoft.com>

diff --git a/dockers/docker-database/Dockerfile.j2 b/dockers/docker-database/Dockerfile.j2
--- a/dockers/docker-database/Dockerfile.j2
+++ b/dockers/docker-database/Dockerfile.j2
@@ -13,10 +13,10 @@ RUN apt-get update
 # Install redis-server
 RUN apt-get install -y redis-tools redis-server
 
+RUN if getent group ${redis_user_gid}; then echo "Error: GID ${redis_user_gid} already exists"; exit 1; fi
 RUN groupmod -g ${redis_user_gid} redis               && \
     chgrp -R redis /etc/redis/                        && \
     chgrp -R redis /var/lib/redis/
-RUN chown -R redis:redis /var/run/redis/
 
 {% if docker_database_debs.strip() -%}
 # Copy locally-built Debian package dependencies
