[action] Update automerge-scan action to send alert and close old PRs.

diff --git a/.github/workflows/automerge_scan.yml b/.github/workflows/automerge_scan.yml
--- a/.github/workflows/automerge_scan.yml
+++ b/.github/workflows/automerge_scan.yml
@@ -6,38 +6,56 @@ on:
 
 jobs:
   automerge_scan:
-    if: github.repository_owner == 'sonic-net'
+    #if: github.repository_owner == 'sonic-net'
     runs-on: ubuntu-latest
     steps:
     - name: Debug
       env:
-        TOKEN: ${{ secrets.TOKEN }}
+        TOKEN: ${{ secrets.GH_TOKEN }}
       run: |
         set -e
+        gh --version
 
         echo ${TOKEN} | gh auth login --with-token
-        gh pr list -R sonic-net/sonic-buildimage -A mssonicbld --json additions,assignees,author,baseRefName,body,changedFiles,closed,closedAt,comments,commits,createdAt,deletions,files,headRefName,headRepository,headRepositoryOwner,id,isCrossRepository,isDraft,labels,latestReviews,maintainerCanModify,mergeCommit,mergeStateStatus,mergeable,mergedAt,mergedBy,milestone,number,potentialMergeCommit,projectCards,reactionGroups,reviewDecision,reviewRequests,reviews,state,statusCheckRollup,title,updatedAt,url > prs.log
+        gh pr list -R sonic-net/sonic-buildimage -A mssonicbld -L 100 -S "label:automerge" --json url,body,title,createdAt,labels,statusCheckRollup > prs.log
         cat prs.log | jq
     - name: Main
+      env:
+        ADO_ID: ${{ secrets.ADO_ID_SUBMODULE }}
+        AZURE_DEVOPS_EXT_PAT: ${{ secrets.AZURE_DEVOPS_EXT_PAT }}
       run: |
         set -e
 
+        date_3d_ago=$(date --date "3 day ago" -u +"%FT%TZ")
+        date_6d_ago=$(date --date "6 day ago" -u +"%FT%TZ")
+        date_28d_ago=$(date --date "28 day ago" -u +"%FT%TZ")
+        date_30d_ago=$(date --date "30 day ago" -u +"%FT%TZ")
+        # date_now format 08:00:00
+        date_now=$(date -u +"%T")
         count=$(cat prs.log | jq 'length')
+        rm -rf old_prs.log
         for ((i=0;i<$count;i++))
         do
           url=$(cat prs.log | jq -r ".[$i].url")
           body=$(cat prs.log | jq -r ".[$i].body")
           title=$(cat prs.log | jq -r ".[$i].title")
+          origin_pr_id=$(echo $title | grep -Eo "\[action\] \[PR:[0-9]*\]" | grep -Eo [0-9]* || true)
           created_at=$(cat prs.log | jq -r ".[$i].createdAt")
-          echo PR: $(($i+1))/$count, URL: $url, createdAt: $created_at, now: $(date -u +"%FT%TZ")
+          echo PR: $(($i+1))/$count, URL: $url, createdAt: $created_at, now: $date_now
           [[ "$url" == "" ]] && continue
           [[ $created_at > $(date --date "1 hour ago" -u +"%FT%TZ") ]] && continue
-          # only check automerge PR.
-          cat prs.log | jq -r ".[$i].labels[].name" | grep automerge || continue
+
+          # update ADO for submodule PR older than 3 days.
+          if [[ $created_at < $date_3d_ago ]] && [ -z "$origin_pr_id" ];then
+            echo "" >> old_prs.log
+            echo $url >> old_prs.log
+            submodule=$(echo $title | grep -Eo "Update submodule .* to the latest HEAD automatically" | sed "s/Update submodule //" | sed "s/ to the latest HEAD automatically//")
+            echo "$submodule FAILED since $created_at" >> old_prs.log
+          fi
 
           checks=$(cat prs.log | jq ".[$i].statusCheckRollup")
           checks_count=$(echo $checks | jq 'length')
-          echo Checks count: $checks_count
+          pr_success=true
           for ((j=0;j<$checks_count;j++))
           do
             check=$(echo $checks | jq ".[$j]")
@@ -47,27 +65,36 @@ jobs:
 
             # EasyCLA success flag:  state=SUCCESS
             # Others success flag:   conclusion in SUCCESS,NEUTRAL
-            # Ignore Azure.sonic-buildimage stage check result. It may be set continueOnError
-            echo "$name" | grep "Azure.sonic-buildimage (" && continue
-            # rerun Azure.sonic-buildimage per day
-            if [[ "$name" == "Azure.sonic-buildimage" ]] && [[ "$conclusion" == "FAILURE" ]];then
-              completedAt=$(echo $check | jq -r '.completedAt')
-              [[ "$completedAt" < $(date --date "2 hour ago" -u +"%FT%TZ") ]] && [[ $(date -u +"%T") < "02:00:00" ]] && gh pr comment $url --body "/azp run Azure.sonic-buildimage"
-            fi
-            # Ignore Semgrep, it has issues.
-            [[ "$name" == "Semgrep" ]] && continue
-            if [[ "$state" == "SUCCESS" ]];then
-              # check pass
-              continue
-            elif [[ "$conclusion" == "SUCCESS" ]] || [[ "$conclusion" == "NEUTRAL" ]];then
-              # check pass
-              continue
-            else
-              echo "$url Check failed!!!"
-              echo $check | jq
-              continue 2
+            # only check Azure.sonic-buildimage currently
+            echo "$name" | grep -v "Azure.sonic-buildimage" > /dev/null && continue
+            [[ "$state" != "COMPLETED" ]] && echo "$name: $state" && continue 2
+
+            success=true
+            ( [[ "$conclusion" == "FAILURE" ]] || [[ "$conclusion" == "CANCELLED" ]] ) && success=false && pr_success=false
+            ! $success && echo "FAIL: $name"
+
+            if [ -z "origin_pr_id" ] && [[ "$created_at" < "$date_3d_ago" ]] && ! $success;then
+              echo "----$name" >> old_prs.log
             fi
           done
+
+          # rerun Azure.sonic-buildimage per day
+          if ! $pr_success;then
+            completedAt=$(echo $check | jq -r '.completedAt')
+            [[ "$completedAt" < $(date --date "2 hour ago" -u +"%FT%TZ") ]] && [[ $date_now < "02:00:00" ]] && gh pr comment $url --body "/azp run Azure.sonic-buildimage"
+          fi
+
+          # Auto cherry pick PRs failed for 3days trigger alert
+          if [[ $created_at < $date_3d_ago ]] && [ -n "$origin_pr_id" ] && ! $pr_success;then
+            origin_pr_url=https://github.com/sonic-net/sonic-buildimage/pull/$origin_pr_id
+            author=$(gh pr view $origin_pr_url --json author | jq .author.login -r)
+            echo "Original author will check."
+            [[ $date_now < "02:00:00" ]] && [[ $created_at > $date_6d_ago ]] && gh pr comment $origin_pr_url --body "@$author cherry pick PR didn't pass PR checker. Please check!!! Auto cherry pick PR will be closed in 24 days.<br>$url"
+            [[ $date_now < "02:00:00" ]] && [[ $created_at < $date_28d_ago ]] && gh pr comment $origin_pr_url --body "@$author cherry pick PR didn't pass PR checker. Please check!!! Auto cherry pick PR will be closed in 2 days.<br>$url"
+            [[ $date_now < "02:00:00" ]] && [[ $created_at < $date_30d_ago ]] && echo "$url Closed" && gh pr close $url
+          fi
+
+          ! $pr_success && continue
           # merge the PR
           echo ========Merging  PR========
           if echo $title | grep "^\[submodule\]";then
@@ -77,3 +104,9 @@ jobs:
           fi
           echo ========Finished PR========
         done
+
+        if wc -l old_prs.log &>/dev/null && [[ $date_now < "02:00:00" ]]; then
+          DISSCUSSION=$(cat old_prs.log | awk '{print}' ORS='<br>')
+          az boards work-item update --org https://dev.azure.com/msazure/ --id $ADO_ID --discussion "$DISSCUSSION" --description "$DISSCUSSION"
+        fi
+
